### ISSUE TITLE
recent posts not showing up

### ISSUE THREAD

**Issue by vikmn** [mmistakes/minimal-mistakes#1022] opened 2017-05-17 16:11 UTC
- [x ] This is a question about using the theme.
I am trying to migrate an earlier version of minimal mistakes to the ruby gem version which would allow me to clear out the various folders (_sass,assets etc). Most of it seems to work apart from the fact that i cant see the posts that reside within the _posts folder on the "Recent posts" section on the home page.

Having re -read the documentation, i am unable to figure out whats missing. Can you help?

**Comment by mmistakes** [comment] 2017-05-17 16:24
Duplicate of #554. See that issue for fixes:

1. Install [Jekyll Related Posts plugin](https://github.com/jumanji27/related_posts-jekyll_plugin)
2. Or replace two files with patched versions

**Closed by mmistakes** 2017-05-17 16:24 UTC

**Comment by adrianba** [comment] 2017-09-22 01:38
#554 seems to be about related post and not recent posts.

I found that recent posts wouldn't show up if I forgot to change `index.md` created by `jekyll new` into `index.html`. This is required by pagination.

**Comment by Blaze349** [comment] 2018-01-01 04:00
Don't forget to create index.html and put 
```YAML
---
layout: home
---
```

**Comment by grantbey** [comment] 2018-01-12 16:09
I had this problem too. The solution was to ensure that index.html was in the root directory and to remove permalink from the front matter. As per [here](https://jekyllrb.com/docs/pagination/) you can't use permalink in the front matter - it will break pagination.

**Comment by ykfq** [comment] 2018-09-13 15:28
I read the docs again and now I'm manage to make it work.

3 files need to be changed:
`vim recent/index.html`
```
---
layout: home
author_profile: true
---
```

`vim _data/navigation.yml`
```
main:
  - title: "Recent"
    url: /recent/
```

`vim _config.yml`
```
paginate: 10 
paginate_path: /recent/page:num/
```

**Comment by voltWu** [comment] 2019-08-28 09:52
I am a new Jekyll, I tried to install minimal-mistakes fallowed this [guide](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/), but when I start my server but there are no post shows.

![QQ截图20190828175113](https://user-images.githubusercontent.com/45677662/63845463-960d4f00-c9bc-11e9-8a85-3af439f2f331.png)
