### ISSUE TITLE
Author Profile not visible on category pages via Jekyll archive plugin

### ISSUE THREAD

**Issue by piyushpaliwal** [mmistakes/minimal-mistakes#2465] opened 2020-03-26 13:18 UTC
## Environment
Jekyll: 3.8.6
Theme Version: 4.19.1
Hosting: Netlify
Demo: https://everythingcrm.in/categories/dynamics-365/
Repo: https://github.com/piyushpaliwal/mmeverythingcrm

- Minimal Mistakes version: 4.19.1
- Ruby gem or remote theme version: 4.19.1
- Jekyll version: 3.8.6
- Git repository URL: https://github.com/piyushpaliwal/mmeverythingcrm
- GitHub Pages hosted (if yes provide URL to site):
- Operating system: Windows
- Site URL with the issue: https://everythingcrm.in/categories/dynamics-365/

## Expected behavior

Upon opening the category or tag page, it should display author profile along with all the posts.

## Steps to reproduce the behavior

Goto the website: https://everythingcrm.in/categories/dynamics-365/

![image](https://user-images.githubusercontent.com/635693/77650899-0485b000-6f92-11ea-8efc-96454dbb792f.png)

## Other
I have also tried adding the `category-archive.md` and `tag-archive.md` page in my local environment but that also does not fix the problem.

![image](https://user-images.githubusercontent.com/635693/77651061-431b6a80-6f92-11ea-9ca1-ef43ef8248f3.png)

**Comment by mmistakes** [comment] 2020-03-26 18:21
Duplicate of #2174

**Comment by piyushpaliwal** [comment] 2020-03-27 05:35
I understand that this is an issue on the archive plugin, as an alternate, what do you recommend? Should I stop the archive plugin and stick to the default archiving?

I take it is going to be too much of an effort to manually create all the archive pages.

**Comment by iBug** [comment] 2020-03-27 06:35
@mmistakes This is actually doable: <https://github.com/iBug/iBug-source/commit/8685c1ecd984529dcb044ba816497313d8896f1e>

Sum up: Archive pages created by JA have types `tag` and `category`, so adding default values for these types of pages works for JA.

I'd be glad if you can point out which part of the documentation this information belongs to so I can submit a PR.

**Comment by piyushpaliwal** [comment] 2020-03-27 09:47
Thanks a lot @iBug, your solution is exactly what I was looking for. I hope this doesn't break anything.

**Closed** 2020-03-27 09:48 UTC
Labels: Type: Duplicate
