### ISSUE TITLE
truncated display on Android device/browser

### ISSUE THREAD

**Issue by Mellivora123** [mmistakes/minimal-mistakes#904] opened 2017-03-16 05:21 UTC
For example, the [homepage](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/) looks like this on my Android browser:

![1739453574](https://cloud.githubusercontent.com/assets/13506936/23982852/2a6575e4-0a4b-11e7-95ae-d6b846038dbd.jpg)

The contents below the picture are not shown.

**Comment by mmistakes** [comment] 2017-03-16 12:37
Hard to tell from the screenshot...

- Does the page just end there?
- What happens to the page when you expand/collapse the "Toggle Menu" button
  ![toggle-menu](https://cloud.githubusercontent.com/assets/1376749/23996289/3cdf84e4-0a23-11e7-96c7-81b71627e663.png)
- Do other pages that use different layouts have the same issue? [Home page](https://mmistakes.github.io/minimal-mistakes/), [Post page](https://mmistakes.github.io/minimal-mistakes/jekyll/welcome-to-jekyll/), [Page with custom sidebar](https://mmistakes.github.io/minimal-mistakes/portfolio/foo-bar-website/)

I don't have an Android device so it's hard for me to isolate what part of the CSS may be causing layout issues. If I had to guess it's related to something in the sidebar as that uses `position: sticky` that may be buggy in your particular browser.

**Comment by Mellivora123** [comment] 2017-03-16 13:19
* Yes
* the toggle menu works fine, but still the post content can not be displayed completely
  ![my screenshot](https://mellivora.space/blog/assets/public/minimal-mistakes-screenshot.jpg)
* they are all ok. But the Post page is too short, I believe the issue would rise again for a long post with *single* layout.

**Comment by mmistakes** [comment] 2017-03-16 14:06
Could be related to [this JavaScript](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/_main.js#L7) that sticks the footer. But not sure since I can't reproduce to debug.

**Comment by mmistakes** [comment] 2017-05-13 15:10
Closing as I can't reproduce. Feel free to reopen with any additional details if this is still an issue with the latest version of the theme.

**Closed by mmistakes** 2017-05-13 15:10 UTC
Labels: Status: Pending Input
