### ISSUE TITLE
css precedence error?

### ISSUE THREAD

**Issue by Kulbhushan-Chand** [mmistakes/minimal-mistakes#1925] opened 2018-11-02 14:35 UTC
Hi @mmistakes , 
I am learning a lot by trying to tweak your theme. Kindly help me with a doubt

## Doubt
I tried to implement the _icons.scss on my website just like you did on your made-mistakes website https://github.com/mmistakes/made-mistakes-jekyll/blob/master/src/assets/stylesheets/_icons.scss

**The only problem I am having is with the css precedence of  fill, width and other attributes** 

### On your website
_I have intentionally added icon--twitter to see the precedence rule. On your website the `.icon--twitter  `takes precedence over `.icon.fill`_

![chrome_2018-11-02_19-46-24](https://user-images.githubusercontent.com/17742733/47921159-eec5a580-ded9-11e8-85c0-68b1fac47d3a.png)

### On my website
_The rule is opposite. and I am not able to set the icon color by using `.icon--facebook` class_

![chrome_2018-11-02_19-47-56](https://user-images.githubusercontent.com/17742733/47921237-1b79bd00-deda-11e8-9a4c-316527ef8f78.png)

**Comment by mmistakes** [comment] 2018-11-02 16:03
Order matters with CSS.
You have a second set of `.icon` styles somewhere and they are overriding `fill` set in `.icon--facebook`.

If you look at the web inspector you can see you have `.icon` styles, then `.icon--facebook`, then a duplicate of `.icon` again. Remove that duplicate set and the `fill` will stay with the color you're setting in `.icon--facebook`.

If you have further CSS questions Stackoverflow and a ton of other tutorial sites is a better place to ask for help.

**Closed by mmistakes** 2018-11-02 16:03 UTC

**Comment by Kulbhushan-Chand** [comment] 2018-11-02 16:16
Thanks and appreciate the help. 🙏
