### ISSUE TITLE
Make it possible wito au

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#1478] opened 2018-01-16 12:32 UTC
- [ ] This is a question about using the theme.
- [x] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

It would be very cool, if it was possible to add more authors to one post, so the theme basically just duplicates the author-profile.html for each author, and often it will just show one author.

**Comment by mmistakes** [comment] 2018-01-16 12:58
Closing as this is a duplicate of #1341

**Closed by mmistakes** 2018-01-16 12:58 UTC
