### ISSUE TITLE
permalink after page filename

### ISSUE THREAD

**Issue by retorquere** [mmistakes/minimal-mistakes#1475] opened 2018-01-15 22:05 UTC
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **GitHub Pages hosted:** yes
- **Operating system:** 

Is it possible to add a `permalink:` entry to the defaults for pages such that every `.md` file will just have the filename as the permalink?

**Comment by Sciss** [comment] 2018-01-15 22:08
Have you tried something like

```
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    value:
      permalink: /:basename/
```

?

**Comment by mmistakes** [comment] 2018-01-15 22:09
You can set `permalink` to whatever you want, the theme doesn't care.

This is a Jekyll core feature, if you need help with setting that up its best to read the official [permalink docs](https://jekyllrb.com/docs/permalinks/) and ask any questions on the [Jekyll Talk forums](https://talk.jekyllrb.com/).

Closing as this isn't a theme issue.

**Closed by mmistakes** 2018-01-15 22:09 UTC

**Comment by mmistakes** [comment] 2018-01-15 22:11
`permalink: /:title/` will take any post or page and output just the title.

```
/_posts/2018-01-15-your-post.md  ~>  /your-post/index.html
about.md  ~>  /about/index.html
```

**Comment by retorquere** [comment] 2018-01-15 22:12
thanks for the tips, and fair enough on this being a Jekyll question.

**Comment by retorquere** [comment] 2018-01-15 22:28
I hesitate to ask now... but setting it as suggested by @Sciss I consistently don't get the css assets. I do get the js assets. Removing the permalink there gets me the css assets back. Otherwise it works flawlessly.

**Comment by mmistakes** [comment] 2018-01-15 22:45
Pretty sure `permalink: /:basename/` isn't a valid key. I tried it and it throws all kinds of Ruby errors and Jekyll doesn't build.

Use `permalink: /:title/` instead like I suggested above.

```yaml
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    value:
      permalink: /:title/
```

**Comment by Sciss** [comment] 2018-01-15 22:52
Yes, sorry it seems `:basename` only works for "pages" but not "documents".

**Comment by retorquere** [comment] 2018-01-16 09:23
I only have pages; my _config looks like

```
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-titles-from-headings

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      permalink: /:title/

_titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false
```

if I use `:title` I get a single directory called `:title` that has:

* index.css
* index.html
* index.js
* index.yml

if I use `:basename` I get a directory per page each with an `index.html` as expected, but no css in the assets dir.

If I omit the permalink, the site is generated as expected in the `_pages` output directory, but I'd really prefer to have the pages appear in the root.

**Comment by Sciss** [comment] 2018-01-16 10:20
Have a look at [my _config.yml](https://github.com/Sciss/minimal-mistakes/blob/homepage2/_config.yml). I defined a new collections "works", with the source files being in `./_works`, and using `permalink: /texts/:path:output_ext` worked for me, so `_works/foo.md` becomes `/texts/foo.html`. I understand you want the output to be `/foo/index.html`, so perhaps `permalink: /:path/` would work?

**Comment by mmistakes** [comment] 2018-01-16 11:55
Thing is you might need to be more specific with `path`... perhaps `path: "_pages"`.

The CSS file in `assets/css` has front matter... which makes it a "page" in Jekyll's eyes. There's probably some sort of bug that is rewritting its permalink based on your front matter defaults in `_config.yml`. It's changing it's path/filename to `index.css` which obviously is going to break things because the theme is expecting `/assets/css/main.css`.

So try the path I suggested above so it only rewrites the permalinks for the files in `_pages`. You still might want to open an issue on `jekyll/jekyll` to see if its a bug. I would create a reduced test case and link to a repo though, because they will want something the can reproduce.

**Comment by retorquere** [comment] 2018-01-16 13:34
OK, that combination gets me further along. The CSS is being created and loaded; it doesn't look right yet but that's something I'll have to tinker with; I'll try to suss out whether it's a Jekyll issue or my misunderstanding of how MM works. Once I have it working I'll do a write-up on how to do a pages-only site with minimal-mistakes.

**Comment by mmistakes** [comment] 2018-01-16 13:38
It's most definitely a how Jekyll works and/or issue. Setting a default permalink in the way you're trying isn't something I've seen many people try.

So that would explain why it's giving you unpredictable results. I would reduce down exactly what you're trying to do, put a sample repo up, and leave that all in an issue on [jekyll/jekyll](https://github.com/jekyll/jekyll).

It seems that setting a default permalink for all `pages` is rewriting static asset pages incorrectly. If anything it should change `/assets/css/main.css` to `main.css`, but the fact that it's rewritting to `index.css` instead of using the file title tells me there's a bug or that use case was never built for.

You might want to do a write-up and post it to the [Jekyll talk forums](https://talk.jekyllrb.com/) as it sounds like something all Jekyll users could benefit from since it's not theme specific.
