### ISSUE TITLE
Categories page 404 error

### ISSUE THREAD

**Issue by adamrushuk** [mmistakes/minimal-mistakes#1764] opened 2018-07-30 07:56 UTC
## Description

Categories are listed correctly in a post (eg. https://adamrushuk.github.io/dsc/powershell/gotcha/msi/dsc-package-resource-gotcha/), but a 404 error appears once you click any category, eg. https://adamrushuk.github.io/categories/#dsc

I've tried to troubleshoot the issue, done a fresh upstream merge, and in the end did a fresh fork yesterday, but cannot see why categories page does not show via GitHub Pages.

## Environment

- Minimal Mistakes version: Latest as of yesterday
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL: https://github.com/adamrushuk/adamrushuk.github.io
- Operating system: Windows
- GitHub Pages hosted (if yes provide URL to site): https://adamrushuk.github.io/

## Expected behavior

I expected all `dsc` posts to show, like your layout posts here: https://mmistakes.github.io/minimal-mistakes/categories/#layout

## Steps to reproduce the behavior

Navigate to https://adamrushuk.github.io/dsc/powershell/gotcha/msi/dsc-package-resource-gotcha/) and note the categories listed: 
![image](https://user-images.githubusercontent.com/11696118/43384414-e2fc31b4-93d5-11e8-8889-100a2df62204.png)

Click on the `dsc` category which will take you here: https://adamrushuk.github.io/categories/#dsc which will show a 404 page:

![image](https://user-images.githubusercontent.com/11696118/43384492-1e3db4d2-93d6-11e8-9cea-fe9e9d5aff51.png)

**Comment by mmistakes** [comment] 2018-07-30 12:44
You need to build the category page. Jekyll or the theme won't do this for you automatically.

The [docs explain this](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#archive-settings). Here's an example categories page you'll need to add to your repo.

https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_pages/category-archive.md

Closing as this is a duplicate of #974

**Closed by mmistakes** 2018-07-30 12:44 UTC

**Comment by adamrushuk** [comment] 2018-07-30 19:49
Thanks for the quick response, I'll look at those links :)

**Comment by adamrushuk** [comment] 2018-08-06 20:04
All works as expected after creating `category-archive.md` in the root of my site, using your example. Thanks again.
