### ISSUE TITLE
iframe embed on page wrecks rendering

### ISSUE THREAD

**Issue by twhite96** [mmistakes/minimal-mistakes#741] opened 2016-12-30 03:38 UTC
I have tried every iframe trick there is on GitHub to fix the issue. It might be with Kramdown. I am not familiar with Liquid or Ruby-- that's not my stack. I was wondering if you have any ideas on how to fix it.

[My Page that doesn't render](https://twhite96.github.io/Livecoding_TV/)

The YAML and iframe:

```html
---
layout: default
title: Livecoding TV
sitemap: true
permalink: /Livecoding_TV/
---  
## Here is Where I Stream My Mistakes

*Enjoy*.

<iframe src="https://www.livecoding.tv/twhite96/embed" width="560" height="315" frameborder="0" scrolling="no" style="display:block; margin: 0 auto;" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
```

**Comment by mmistakes** [comment] 2016-12-30 04:34
Well you're in luck I'm 99.99999% sure the issue isn't Liquid or Ruby related.

I see a couple of things you might need to clear up to get it working.

**Issue 1:** The main content area is missing some divs used for presentation which is why the page looks managed. You're using `layout: default` when you probably want `layout: single` instead.

**Issue 2:** Kramdown does appear to be ripping out some markup from the `iframe` embed you pasted above. It used to do this with YouTube embeds back in the day and you had to do a dance with removing `allowFullScreen` and adding a space before the closing `</iframe>` tag.

I don't think this will help in this case. Kramdown does have a way of instructing it not to process a block of content as Markdown and leave the HTML alone. Take a look at the [documentation](https://kramdown.gettalong.org/syntax.html#html-blocks) for more on that.

Essentially what you do is add an attribute (`markdown="0"`) to your tag (sometimes you need to wrap in a `div` and apply it there) to get the HTML to output untouched.

```html
<iframe markdown="0" src="https://www.livecoding.tv/twhite96/embed" width="560" height="315" frameborder="0" scrolling="no" style="display:block; margin: 0 auto;" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
```

or possibly this:

```html
<div markdown="0">
  <iframe src="https://www.livecoding.tv/twhite96/embed" width="560" height="315" frameborder="0" scrolling="no" style="display:block; margin: 0 auto;" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
</div>
```

**Issue 3:** After that depending on how the video iframe renders inside of the main content container you may need to play with some JavaScript. The theme ships with [FitVids.js](http://fitvidsjs.com/) that adds a wrapper element around video players (YouTube, Vimeo, Blip.tv, Viddler, Kickstarter) and then with the help of some CSS responsively sizes it to fill the width.

Livecoding.tv isn't natively supported with FitVids.js but they do offer a way to add [custom selectors](https://github.com/davatron5000/FitVids.js#add-your-own-video-vendor) for any video vendor you want. To do that you'd need to edit a single line of JavaScript in [`assets/js/_main.js`](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/_main.js#L26) to something like:

```js
$("#main").fitVids({ customSelector: "iframe[src^='https://www.livecoding.tv']"});
```

Then rebuild the script following the [instructions here](https://mmistakes.github.io/minimal-mistakes/docs/javascript/).

If you don't want bother with editing the JS you could possibly wrap the `iframe` like so, which is what FitVids is doing automatically... giving it the CSS class it needs to resize responsively.

```html
<div class="fluid-width-video-wrapper">
  <iframe src="https://www.livecoding.tv/twhite96/embed" width="560" height="315" frameborder="0" scrolling="no" style="display:block; margin: 0 auto;" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
</div>
```

Hope this helps point you in the right direction.

**Comment by twhite96** [comment] 2017-01-21 18:11
It didn't work so I just scrapped it. Not sure why or what happened but it didn't work no matter what I tried.

**Closed** 2017-03-23 23:11 UTC
Labels: Type: Support
