### ISSUE TITLE
Footer not visible in two column view 

### ISSUE THREAD

**Issue by kcha** [mmistakes/minimal-mistakes#1587] opened 2018-03-17 02:42 UTC
- [ ] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [x] I believe this to be a bug with the theme.
  - [x] I am using the latest version of the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.10.1
- **Jekyll version:** 3.7.3
- **GitHub Pages hosted:** not yet
- **Operating system:** Mac 10.13.3

---

I'm just starting to get familiar with this theme on my local machine. I noticed that in the two-column layout with the sidebar, even if there minimal content in the main section such that scrolling is not required, you still need to scroll down to reveal the footer. An example of this can be seen when you load main page of the example website (see screenshots below). The problem seems to fix itself when you change to the single-column layouts. Is it possible to keep the footer visible in all views? Thanks!

<img width="1082" alt="screen shot 2018-03-16 at 10 29 46 pm" src="https://user-images.githubusercontent.com/194053/37550816-10579aa8-296a-11e8-82c6-30fa6786d0ff.png">

Scrolling down reveals the footer:

<img width="1083" alt="screen shot 2018-03-16 at 10 29 39 pm" src="https://user-images.githubusercontent.com/194053/37550819-1e84b430-296a-11e8-97e1-e105a189c905.png">

**Comment by mmistakes** [comment] 2018-03-17 04:07
Not sure this is a bug. There is some JavaScript that calculates the screen height to push the footer to the absolute bottom.

Before this, pages with little to no content that didn't fill the viewport, would cause the footer to float in the middle of the page because the content wasn't tall enough to push it down.

Try adding some posts and content and see if things improve for you.

**Comment by kcha** [comment] 2018-03-17 11:30
I tried adding some content in two scenarios, one with enough content to overfill the viewport and one without. In the first case, it behaves as expected -- the footer immediately follows the end of the content as you scroll down. In the second case, it's still the same as what I showed above. I found one example online of a page that has minimal content, but the footer is visible in all views: https://zenglix.github.io/links/, which to me is the behaviour I was expecting. It looks like the page is using an older version of the theme and I haven't checked what may have changed. Although if you think the current behaviour is to be expected, then I will drop this issue. Thanks!

**Comment by mmistakes** [comment] 2018-03-17 13:18
I did some testing with a page that had no content and everything looks as expect.

There's some extra whitespace in the main content area, but that's due to some sidebar CSS that stretches it fill the height of the viewport. This is needed to make it "stick" on pages that have some extra content.

What you can do is use your browser's web developer tools and inspect elements. It'll give you a better idea of what's going on... like the following screenshot (you can see how the sidebar stretches even though it isn't really that tall with content).

![screen shot 2018-03-17 at 9 12 52 am](https://user-images.githubusercontent.com/1376749/37555818-0ffa24cc-29c4-11e8-89ce-516dcdfb98f7.png)

Closing as I everything appears to be working as intended. If you think otherwise, have a public repo that replicates the problem, and indicate what browser it's doing it in I can dig in further. Feel free to reopen the issue is that's the case.

**Closed by mmistakes** 2018-03-17 13:18 UTC

**Comment by mmistakes** [comment] 2018-03-17 13:19
Also if this is an issue for you... you can remove the [`sticky` class from the sidebar](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/sidebar.html#L2). It will remove the CSS that gives it a `height` to fill the viewport.
