### ISSUE TITLE
Custom comment appears under the footer

### ISSUE THREAD

**Issue by sunete** [mmistakes/minimal-mistakes#2549] opened 2020-06-01 02:49 UTC
## Environment
- Minimal Mistakes version: 4.19.1
- Jekyll version: 3.0.6
- Git repository URL: https://github.com/sunete/sunete.github.io
- GitHub Pages hosted (if yes provide URL to site): https://sunete.github.io/
- Operating system: Windows 10

## Expected behavior
I tried to custom comment. But the custom comment box appeared under the footer. What shuold I do to fix it? 

## Steps to reproduce the behavior
I tried to custom comment. The comments provider I used is [valine comment](https://valine.js.org/). But when I added html code to the [_includes\comments-providers\custom.html](https://github.com/sunete/sunete.github.io/blob/master/_includes/comments-providers/custom.html) , the comment box appeared under the footer.

![below](https://s1.ax1x.com/2020/06/01/t8QCAf.png)

## Other
**I'm not very good at programming. Could you help me fix my code please?**
Custom comment code in [_includes\comments-providers\custom.html](https://github.com/sunete/sunete.github.io/blob/master/_includes/comments-providers/custom.html)
```
<script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>
<script src='//unpkg.com/valine/dist/Valine.min.js'></script>
<body>
    <div id="vcomments"></div>
    <script>
        new Valine({
            el: '#vcomments',
            appId: 'fBruNownJxl4LxbgbUmhSNbG-gzGzoHsz',
            appKey: 'iLHQpvO6X1Quor49czkLLi6m',
            visitor: true
        })
    </script>
</body>
```

**Comment by iBug** [comment] 2020-06-01 05:26
Duplicate of #2343.

**Comment by sunete** [comment] 2020-06-01 06:24
I tried to run `JEKYLL_ENV=production bundle exec jekyll build` as you [mentioned](https://github.com/mmistakes/minimal-mistakes/issues/2343#issuecomment-565305655) in the issue #2343 , but it didn't work. Then I tried to run shell below, the comment still in the wrong position like before. Is there any fault in my operation?

![shell](https://s1.ax1x.com/2020/06/01/t8qxte.png)

**Comment by iBug** [comment] 2020-06-02 13:57
Your addition of an extra `<body>` tag looks erroneous. Perhaps you should try removing the wrong tags?

**Comment by sunete** [comment] 2020-06-03 00:13
Even if I remove the `body` tag it still in the wrong position. I commited it to the repository so you can have a look.

My last commit: [Enable custom comment for testing](https://github.com/sunete/sunete.github.io/commit/a738b14dd64e4b5457b6e4ab34e5da87c545947c).

My website: [Example of a comment box in the wrong positon.](https://sunete.github.io/tutorial/set-jekyll-env-production/)

Besides, I found that no matter what I added in `custom.html` , it would appear under the footer.For example, I only put `<p>I have a cute cat.</p>` in `custom.html` , this sentence will appear under the footer like before.
![image.png](https://i.loli.net/2020/06/03/EpUkZDlvgQRCh3n.png)

**Comment by mmistakes** [comment] 2020-06-03 02:14
The issue is `/comments-providers/custom.html` are for scripts only. This include is loaded after the footer.

You need to edit `_includes/comments.html` [on this line](https://github.com/sunete/sunete.github.io/blob/master/_includes/comments.html#L157) and replace with comment HTML you need there. Probably the easier thing would be to drop in your scripts there too and forget about `/comments-providers/custom.html`

**Closed** 2020-06-03 02:33 UTC
Labels: Type: Support
