### ISSUE TITLE
Sigma.js on minimal mistakes

### ISSUE THREAD

**Issue by jaruizso** [mmistakes/minimal-mistakes#1141] opened 2017-07-28 10:38 UTC
- [X ] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---
Hi there,

I am tryng to use sigma.js on my website, but I cannot make it work. So actually I dont know if it supports javascript. In theory yes as I can see from the short guide, but I am not very familiar with javascript, so probably I am missing something.

What i have done is to insert the sigma.js folder in my repository: https://github.com/jaruizso/jaruizso.github.io

Then i try to make a test by running it on jaruizso.github.io/teaching with the following code:
![captura de pantalla 2017-07-28 a les 12 32 27](https://user-images.githubusercontent.com/12252768/28713914-6416018c-7391-11e7-9e05-ff4669c4123f.png)

nmp is installed and I can run it on my computer.

**Comment by mmistakes** [comment] 2017-07-28 12:18
The issue is the path used in your `script`. `/sigma.js` is just the folder. You need to actually point it to a JavaScript file. Which looking at your repo might be `/sigma.js/build/sigma.min.js`. I'm unfamiliar with Sigma so I would check their docs what files or plugin scripts are necessary to load.

You'll probably want to use Jekyll's [`relative_url`](https://jekyllrb.com/docs/templates/) filter to make sure the path resolves correctly as well.

I'd do something like:

```js 
<script src="{{ '/sigma.js/build/sigma.min.js' | relative_url }}"></script>
```

As this is a "how do I use Jekyll" issue and not theme specific I'm closing. If you need further help I'd suggest reading the Jekyll docs or asking for help [talk.jekyllrb.com](https://talk.jekyllrb.com) or Stackoverflow.

**Closed by mmistakes** 2017-07-28 12:18 UTC
