### ISSUE TITLE
Add support for a multi-language website

### ISSUE THREAD

**Issue by samuel-carleial** [mmistakes/minimal-mistakes#2195] opened 2019-06-25 20:02 UTC
## Summary

Apparently Jekyll has no built-in support for multi-language static sites. Wouldn't that be a nice improvement? I have looked at the internet, but there is no simple answer. What is your personal suggestion on how to improve the theme, by adding this feature?

## Motivation

I would like to make a personal website where I have support for multiple languages.

## Drawbacks

I cannot find one, except for the programming time

**Comment by mmistakes** [comment] 2019-06-25 20:10
Since Jekyll doesn't offer a built in way of doing this, nor are the plugins that do add this functionality white-listed on GitHub Pages there's no good way for the theme to support it.

It would add a layer of complexity I'm not comfortable baking into the theme. There have been talks of adding i18n support into Jekyll core, but I'm not sure if that work is still being considered. If/when they do I wouldn't mind revisiting this for the theme.

Closing as this is a duplicate of several older issues: #1748, #917, #612, #50

**Closed by mmistakes** 2019-06-25 20:10 UTC
