### ISSUE TITLE
teaser image

### ISSUE THREAD

**Issue by mattiamazzoli** [mmistakes/minimal-mistakes#1873] opened 2018-10-04 17:00 UTC
Hello everybody,
I was trying to uncomment the teaser field in the _config.yml file in order to have a big picture at the top of the main page and nothing appears in the page...
Did somebody try to do this or there is another trick?
Moreover in the tutorial I read that it works in the "related posts" section, while I just see the "recent posts" section...
Is this correlated to the above problem?

I use ubuntu16 and Git-Hub Pages, single layout

Thanks
Great theme tho!

**Comment by mmistakes** [comment] 2018-10-04 17:04
The teaser field in `_config.yml` doesn't have anything to do with setting images in the posts or in archive listings. You'll need to customize the theme to do this.

See this issue #1717 for ideas and code.

Closing as this is a duplicate of that issue.

**Closed by mmistakes** 2018-10-04 17:04 UTC
