### ISSUE TITLE
Hide all masthead links inside the hamburger icon on **mobile devices**

### ISSUE THREAD

**Issue by Kulbhushan-Chand** [mmistakes/minimal-mistakes#1945] opened 2018-11-16 11:36 UTC
## Summary
Hide all masthead links inside the hamburger icon on **mobile devices.**

## Motivation

Some of the links looks odd-one-out, while other rests peacefully inside the hamburger icon
![image](https://user-images.githubusercontent.com/17742733/48617753-55a88b80-e9bd-11e8-8495-996bb1b3ac65.png)

## Drawbacks
Nothing, since this feature will activate only in mobile devices, people will like it (at least I'll ❤️ it)

## How to do it?
Something related with breakpoints. I am not yet capable to understand all the intricacies without not messing something up.

**Important Note:-** If you are not going to consider this enhancement, please give me some pointers, so I can do it myself without messing other things in the theme.

**Comment by mmistakes** [comment] 2018-11-16 11:55
Duplicate of #1418, #1301

**Closed by mmistakes** 2018-11-16 11:55 UTC

**Comment by Kulbhushan-Chand** [comment] 2018-11-16 12:22
Thanks for the pointer
