### ISSUE TITLE
Question: really wide pages?

### ISSUE THREAD

**Issue by haji-ali** [mmistakes/minimal-mistakes#2511] opened 2020-04-30 21:41 UTC
In pages in which the author-profile is disabled, is there a way to have the page be 100% wide?
Using `classes: wide` the page is gets to the right edge but there is still empty space on the left where the author-profile usually is.

**Comment by mmistakes** [comment] 2020-04-30 23:33
Duplicate of #2453

**Closed by mmistakes** 2020-04-30 23:33 UTC
