### ISSUE TITLE
Spotify as a sidebar link

### ISSUE THREAD

**Issue by nelsonmestevao** [mmistakes/minimal-mistakes#1794] opened 2018-08-19 18:02 UTC
I think spotify would be a nice addition and I would be willing to make a pull request adding it.

Would it be of any interest?

**Comment by mmistakes** [comment] 2018-08-20 12:51
Closing as this is a duplicate of several other issues like #1676 

Additional sidebar links can be added using [`/includes/author-profile-custom-links.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/author-profile-custom-links.html) or creating your own layout overrides as [per the docs](https://jekyllrb.com/docs/themes/#overriding-theme-defaults).

**Closed by mmistakes** 2018-08-20 12:51 UTC
Labels: Status: Won't Fix, Type: Duplicate
