### ISSUE TITLE
Site search

### ISSUE THREAD

**Issue by icicimov** [mmistakes/minimal-mistakes#588] opened 2016-10-14 09:58 UTC
- [x] This is a question about using the theme.

---

Hi Michael,

I 'm thinking about setting up a site search function and came across this plugin https://github.com/slashdotdash/jekyll-lunr-js-search, that looks not too complicated to implement. Was wondering what are your thoughts on this and is there maybe a guide you would recommend for this functionality?

Thanks

**Comment by justinrummel** [comment] 2016-10-14 11:18
I've got it running on my site. Warning, it doubles the time it takes to generate a site. I was finishing in 20s, but now with Lunt it takes over 40s. 

https://www.justinrummel.com/search/

**Comment by mmistakes** [comment] 2016-10-14 13:38
@icicimov I don't have first-hand experience with Lunr but have used similar solutions. The instructions on  that repo seem pretty good but if you need more of a "tutorial" there's quite a few if you search around.

- http://jekyll.tips/jekyll-casts/jekyll-search-using-lunr-js/
- http://rayhightower.com/blog/2016/01/04/how-to-make-lunrjs-jekyll-work-together/
- http://katydecorah.com/code/lunr-and-jekyll/
- http://scotthorsfield.me/technology/2016/01/21/Searching-Jekyll-Post-and-Page-Content-with-lunr-js/

I'll echo what @justinrummel said about build times. I haven't read Lunr docs to know if this is true but I would assume it work by querying a `.json` index file with all of your post data in it. Depending on the complexity of that is what makes build times go up. 

Other Jekyll search solutions I've used had you build a `.json` file that loops over every post and then you can pull out things like post titles, post excerpts, etc. If Lunr is dumping the full content of every post that would certainly increase the bloat.

**Comment by justinrummel** [comment] 2016-10-14 13:42
FYI; here are my commits for adding Lunr:

- [_config.yml](https://github.com/justinrummel/jr.com-mm/commit/da12b6944e4a7caf3965e443c1b16420e171d8ae)
- [A LOT MORE](https://github.com/justinrummel/jr.com-mm/commit/d2d0d620c5a5d0ddca283ecfe2eeb3b322f5b3b2)

**Comment by icicimov** [comment] 2016-10-15 09:17
@mmistakes and @justinrummel, thank you both for your help and useful tips.

Pretty much following Justin's commit that he generously shared I have created the following structure:

_config.dev.yml:
```
# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - json
  - jekyll-lunr-js-search

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - json
  - jekyll-lunr-js-search

lunr_search:
  excludes: [rss.xml, atom.xml]
  stopwords: "stopwords.txt"
  min_length: 3
  js_dir: "/assets/js/lunr"
```

Gemfile:
group :jekyll_plugins do
  gem "jekyll-lunr-js-search"
end

_plugins/
├── jekyll_lunr_js_search.rb
└── related_posts.rb

assets/js/lunr/
├── date.format.js
├── jquery-1.12.4.min.js
├── jquery.lunr.search.js
├── lunr.min.js
├── mustache.min.js
├── search.min.js
└── URI.min.js

_includes/scripts.html

_includes/search.html

_pages/search.md:
```
---
author_profile: true
type: pages
layout: single
title: Search
permalink: /search/
exclude_from_search: true
---
{% include search.html %}
```

but during the local site build the **index.json** file is not being created and I get  ERROR `/blog/assets/js/lunr/index.json' not found.

To me it looks like the plugin is not working for some reason. Do I need to do anything else apart from the above to get the plugin activated?

Thanks again for your help, very much appreciated.
Igor

**Comment by icicimov** [comment] 2016-10-15 10:57
Ok, seams I misinterpreted the plugin help page:

> This Jekyll plugin handles the generation of a lunr.js compatible .json index file. Runtime search configuration is provided by a simple jQuery plugin.

and thought the plugin will generate the **assets/js/lunr/index.js** file instead of the **_sites/assets/js/lunr/index.json** file ... doh.

Still not working for some reason but after I dropped in a index.json file the plugin generated the index.json file ready for jquery to search but still blank.

**Comment by justinrummel** [comment] 2016-10-16 01:19
I've found Lunr to be very picky about the gem order.  Please see my Gemfile and _config.yml and replicate.

**Comment by twhite96** [comment] 2017-02-10 04:59
@justinrummel I have Lunr set up, it builds. I have tried to get your layout going with the Tag and Category archives, but I get build warnings: single layout doesn't exist. Then when visiting my site, I see the navigation but it says page not found, when I know for a fact I added those pages. I also don't have the hamburger menu for links that don't fit on the main page. Can you have a look at my repo? https://github.com/twhite96/twhite96.github.io

Thank you.

**Comment by mmistakes** [comment] 2017-02-10 13:27
@twhite96 I think the issue is your JavaScript. If you fire up the console in your browser you'll see a bunch of errors. That's why the hamburger menu isn't working.

![console-errors](https://cloud.githubusercontent.com/assets/1376749/22828337/ab180734-ef6a-11e6-899a-37c40804d023.jpg)

**Comment by justinrummel** [comment] 2017-02-10 14:20
@twhite96 the "single" is a layout https://github.com/twhite96/twhite96.github.io/blob/master/_layouts/single.html

Not sure why it's not picking it up when it's obviously there in your repo.  Only diff I can see between yours and mine is I have removed "{% include base_path %}" from the 5th line.

In addition I use "compress" in my default layout. https://github.com/justinrummel/jr.com-mm/blob/jr-branch/_layouts/default.html

**Comment by mmistakes** [comment] 2017-02-10 16:26
@twhite96 Looking at your `Gemfile.lock` you're using some outdated gems... eg. Jekyll isn't the latest. So I would `bundle update` to make sure you're current.

And you're using the theme-gem along with having all of the `_layouts`, and `_includes` with your repo. And when you do that your local versions overwrite anything in the bundled theme gem, which could be why you're getting missing layout errors.

If you're using the theme gem then remove `_layouts`, `_includes`, `_sass`, etc... unless of course you modified any of those files and want them to replace whats in the default theme.

Or if you're not using the theme gem just remove `theme: minimal-mistakes-jekyll` from your **_config.yml**

**Comment by twhite96** [comment] 2017-02-10 23:03
Thanks @mmistakes and @justinrummel. I can't seem to get the search page running though. Says page not found. Everything else works after I fixed the js and deleted `_layouts` `_incluses`, and `_sass`. Not sure what's going on there. Can anyone help?

**Comment by twhite96** [comment] 2017-02-10 23:33
@mmistakes and @justinrummel seems that the tag archive and category archive works locally but only as a directory when running `jekyll serve`. Search doesn't even appear. But when running it at my production site, https://twhite96.surge.sh, pages aren't found. Something weird going on here.

**Comment by justinrummel** [comment] 2017-02-11 14:42
@twhite96 I was able to clone your repo locally and noticed you don't have the _pages section setup correctly.  It should be files ending in .html will be converted to /filename/.  Therefore, take a look at my [_pages](https://github.com/justinrummel/jr.com-mm/tree/jr-branch/_pages) and use the same format while at the same time remove the .md files.  **WARNING**, I've injected an element from @mmistakes hpstr to arrange all the tags at the top, then use CSS to display correctly... so your site may look different than mine.

In addition, I updated your _config to state 

``` bash
include:
  - .htaccess
  - _pages
```

Tags, Categories, and Search display correctly now.  

Lastly, You did cleanup _includes as suggested when using the gem version of mm, however, you do need to keep the _includes/script.html as seen on my site as a gem override.  Once that was in place, searched worked locally.

![screen shot 2017-02-11 at 9 40 48 am](https://cloud.githubusercontent.com/assets/466605/22854515/2eb66c74-f03e-11e6-9e54-c17dd0ac8330.png)

**Comment by twhite96** [comment] 2017-02-12 01:42
Thank you @justinrummel! Got it working.

**Comment by icicimov** [comment] 2017-02-16 21:40
Sadly I never got this working on my site :-(

**Comment by jhabdas** [comment] 2017-02-24 21:54
Here's my favorite Jekyll search experience to date: https://developmentseed.org/blog/multilingual-jekyll-sites/

**Comment by mmistakes** [comment] 2017-04-27 20:06
@icicimov As others have gotten this to work I'm going to close it out. If you have additional information to provide to help resolve it feel free to re-open.

**Closed by mmistakes** 2017-04-27 20:06 UTC
Labels: Type: Support

**Comment by twhite96** [comment] 2017-04-28 04:26
@jhabdas how was that accomplished?

**Comment by jhabdas** [comment] 2017-04-28 04:27
lunr.js. they may even have a post about it on that site. those are the guys who created healthcare.gov
