### ISSUE TITLE
Author social buttons not showing up

### ISSUE THREAD

**Issue by StephenCavender** [mmistakes/minimal-mistakes#421] opened 2016-08-09 12:02 UTC
- [ ] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 3.3.6
- **`github-pages` or `jekyll` gem version:** 3.1.6
- **Operating system:** Windows 10

---

## Expected behavior

Social links show up under author profile.

## Steps to reproduce the behavior

https://github.com/StephenCavender/stephencavender.github.io
1. Forked theme
2. Customized and created posts
3. Updated to 3.3.6

**Comment by mmistakes** [comment] 2016-08-09 12:07
Social links are there. You likely have an ad blocker running which tend to go overboard and remove Font Awesome icons in attempt to rid the page of bulky social sharing scripts (which this theme doesn't use).

Here's the upstream issue if you want more context. https://github.com/FortAwesome/Font-Awesome/issues/1799

![author](https://cloud.githubusercontent.com/assets/1376749/17515724/2427b20e-5e08-11e6-92fd-0e48789849a5.jpg)

Closing as this is a duplicate of #413

**Closed by mmistakes** 2016-08-09 12:07 UTC
