### ISSUE TITLE
Two clicks required to select items on iOS devices

### ISSUE THREAD

**Issue by david-w** [mmistakes/minimal-mistakes#315] opened 2016-05-12 15:53 UTC
Your Jekyll theme is amazing!  Thank you.

Sorry if this has been addressed before.  I have to click twice on menu items and links on IOS devices.

Seems like this autocomplete bug? [https://bugs.jqueryui.com/ticket/10544](url) 

Some ideas here as well. [http://stackoverflow.com/questions/25286685/autocomplete-requires-you-to-click-twice-in-ios-after-update-to-1-11-0](url)

**Comment by mmistakes** [comment] 2016-05-12 16:39
The theme isn't using [jQueryUI](https://jqueryui.com/) so that's likely not the culprit.

I believe this is related to the touch behavior of iOS devices to distinguish between "clicks" and touches. You can use a polyfill like [FastClick](https://github.com/ftlabs/fastclick) to get around it.

**Comment by jhabdas** [comment] 2016-05-30 17:25
The culprit is indeed iOS behavior and is [summarized in detail by Nick Zakas](https://www.nczonline.net/blog/2012/07/05/ios-has-a-hover-problem/). FastClick was designed to overcome the [the 300ms delay](http://habd.as/on-touch-events-mobile-web-app-usability/) for mobile touch events and seems like the wrong approach to fix this unexpected behavior. But I can't just say that and not leave it at that. Here are two workable solutions:

- Remove or comment out [L237-L241](https://github.com/mmistakes/minimal-mistakes/blob/2e2e5bfb5122f68f1092d4789ce563eef3baa4ba/assets/_scss/_navigation.scss#L237-L241) of `_navigation.scss` and then `npm i && npm run build:css`. This is the easiest approach but, unfortunately, causes the underline animation to stop functioning both on desktop and mobile.
- Alternatively, and as pointed out in the comments on Nick's post, one can use feature detection to determine if the browser supports touch events and, if they do, don't show the animation at all. Not showing the animation on touch devices feels like the best approach given the animation will continue to work on desktop and isn't intended to be shown on touch tap anyway.

**Comment by mmistakes** [comment] 2016-05-30 19:15
Thanks @jhabdas for digging up this info. Will have to see what I can come up with.

**Comment by jhabdas** [comment] 2016-05-30 20:19
No need, unless you want to change the breakpoint: https://github.com/mmistakes/minimal-mistakes/pull/330 ;)

**Comment by mmistakes** [comment] 2016-05-31 16:40
Fixed in MM 3.2.1 15f4ac96417621fa71b397f44b935ebf3abca6c1... I think :wink:

**Closed by mmistakes** 2016-05-31 16:40 UTC
Labels: Type: Enhancement

**Comment by jhabdas** [comment] 2016-05-31 21:33
Confirmed fixed. Thanks for including this enhancement. Having a blast porting over from HPSTR.

**Comment by david-w** [comment] 2016-06-09 19:34
Thanks so much for all your work!
