### ISSUE TITLE
feed.xml works locally but not online

### ISSUE THREAD

**Issue by ImAlexisSaez** [mmistakes/minimal-mistakes#1145] opened 2017-08-02 09:41 UTC
- [x ] This is a question about using the theme.
- [ ] This is a feature request.
- [x ] I have updated all gems with `bundle update`.
- [x ] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- **Minimal Mistakes version:** 4.4.2
- **`github-pages` or `jekyll` gem version:** 
- **Operating system:** Windows 10

---

## Expected behavior

Hello,

I have a minor issue with the theme: when I check it locally (with `bundle exec jekyll serve`) I see the file `feed.xml` perfectly, but it doesn't show online.

I moved the blog posts away from the homepage to a section named "blog". Could that be the reason?

Thanks.

## Steps to reproduce the behavior

Repository: [https://github.com/ImAlexisSaez/ImAlexisSaez.github.io](https://github.com/ImAlexisSaez/ImAlexisSaez.github.io).
Web: [https://imalexissaez.github.io/](https://imalexissaez.github.io/).

**Comment by mmistakes** [comment] 2017-08-02 10:52
Duplicate of #1144 

Change [`plugins:`](https://github.com/ImAlexisSaez/ImAlexisSaez.github.io/blob/master/_config.yml#L185) in your `_config.yml` back to `gems:`. GitHub Pages doesn't use the version of Jekyll that accepts this key change. What's happening is the Jekyll Feed plugin isn't loading, so your `feed.xml` file isn't being created.

Once [github/github-pages](https://github.com/github/pages-gem) updates to support Jekyll 3.5 `plugins` should work.

**Closed by mmistakes** 2017-08-02 10:52 UTC
