### ISSUE TITLE
How 

### ISSUE THREAD

**Issue by zfrenchee** [mmistakes/minimal-mistakes#551] opened 2016-09-22 21:38 UTC
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

How would you go about setting up URLs from the base site which redirect to foreign sites? 

So if foo.com is my minimal-mistakes jekyll site, I'd like to set up foo.com/bar to redirect to bar.com.

**Comment by mmistakes** [comment] 2016-09-22 21:44
This isn't something theme related so I'm going to close it. 

But what you want is to use .htaccess redirects if you have control over the server you're hosting with.

https://css-tricks.com/snippets/htaccess/301-redirects/

Or if you're hosting with GitHub use the bundled Jekyll redirect plugin to set them up.

https://github.com/jekyll/jekyll-redirect-from

**Closed by mmistakes** 2016-09-22 21:44 UTC

**Comment by zfrenchee** [comment] 2016-09-22 21:55
I'm hosting with github but the jekyll redirect plugin doesn't actually work. I've sent them a message using their contact form. Their article only describes redirecting *from* not *to* so even though the gem supports redirecting *to* I wonder whether it might not work with github pages?

**Comment by mmistakes** [comment] 2016-09-22 23:19
I've only ever used .htaccess 301 redirects so not much help.

In my limited testing the Jekyll redirect plugin worked as advertised. Since I have nothing to do with plugin I'd suggest submitting an issue there. Provide examples and a public Jekyll repo so they can reproduce the issue and help troubleshoot otherwise you'll likely never get resolution.

**Comment by ElectricRCAircraftGuy** [comment] 2020-11-03 09:07
I just want to report back that the [jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from) plugin worked perfectly with GitHub pages. The instructions were super easy to follow, too.

Here's an example: this URL (https://electricrcaircraftguy.github.io/20190919-post_ubuntu_18_todos.html) and this one (https://gabrielstaples.com/2019/09/19/ubuntu-18-post-install-steps.html) both perfectly redirect to this one (https://gabrielstaples.com/ubuntu-18-post-install-steps/).
