### ISSUE TITLE
Extra space added when using a feature_row

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#2327] opened 2019-11-19 07:41 UTC
Extra space added when using a feature_row in layout `single`.

## Environment

- Minimal Mistakes version: 4.17.2
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL: https://github.com/motionsplan/motionsplan-dk-jekyll/blob/gh-pages/_posts/2019-11-19-regler-styrkeloft.md
- GitHub Pages hosted (if yes provide URL to site):
- Operating system:

## Expected behavior

There should be no extra space in front of the feature row.

## Steps to reproduce the behavior

See https://github.com/motionsplan/motionsplan-dk-jekyll/blob/gh-pages/_posts/2019-11-19-regler-styrkeloft.md

Which gives this result:

![Screenshot - 2019-11-19T083854 829](https://user-images.githubusercontent.com/148026/69126351-4e243280-0aa8-11ea-80cf-175e87d72df2.png)

## Other

It can be seen on the live site here: https://www.motionsplan.dk/powerlifting-rules/

**Comment by mmistakes** [comment] 2019-11-19 13:10
Looks like it has to do with the right sidebar. If you inspect it you can see it's pushing over into the main content column some, which pushes the feature row down.

![image](https://user-images.githubusercontent.com/1376749/69149098-c0dedf00-0aa3-11ea-857d-8342b6b60643.png)

When the right sidebar isn't being floated the feature row has enough room and fits.

![image](https://user-images.githubusercontent.com/1376749/69149208-013e5d00-0aa4-11ea-94c4-691d1a3ab27f.png)

Not sure what the fix is yet.

**Comment by iBug** [comment] 2019-11-19 16:44
Duplicate of #2263

**Comment by mmistakes** [comment] 2019-11-19 16:52
It'll likely break other things but giving `feature__wrapper` an inline style of `display: inline-block` fixes the wrap with the sidebar.

![image](https://user-images.githubusercontent.com/1376749/69167453-ffd05d00-0ac2-11ea-8300-aa39511a0dda.png)

**Comment by iBug** [comment] 2019-11-19 17:02
@mmistakes Perhaps something like this would be helpful without breaking anything?

```css
.layout--single .feature__wrapper {
  display: inline-block;
}
```

Tried this in a few MM-themed sites, didn't notice any failure so far.

**Comment by mmistakes** [comment] 2019-11-19 17:16
@iBug that change looks harmless to me if you want to submit a PR with the fix.

**Closed** 2019-11-22 14:15 UTC
Labels: Status: Accepted, Type: Bug, Type: Duplicate, Type: Support
