### ISSUE TITLE
title_seperator not working for "|"

### ISSUE THREAD

**Issue by deepaksood619** [mmistakes/minimal-mistakes#1201] opened 2017-08-25 10:17 UTC
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I believe this to be a bug with the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** - 4.5.1
- **Jekyll version:** - 3.5.2
- **GitHub Pages hosted:** yes
- **Operating system:** - macOS Sierra

## Expected behavior

title_separator          : "|"
<img width="536" alt="screen shot 2017-08-25 at 3 40 31 pm" src="https://user-images.githubusercontent.com/13206612/29709991-2e39662c-89ac-11e7-86fd-ed45fc392005.png">

The title doesn't show the title separator as specified, when pipe is used (above image)

title_separator          : "-"
<img width="492" alt="screen shot 2017-08-25 at 3 41 22 pm" src="https://user-images.githubusercontent.com/13206612/29709999-31924956-89ac-11e7-8fa3-5eb3cb7dc8f3.png">

I tried it with "," "x" and it's working, it seems that title_seperator : "|" is only not working (pipe |)
Its not working in any page, home, blog, etc.

**Comment by mmistakes** [comment] 2017-08-25 11:01
You have to use the HTML entity. The `|` pipe character means something in YAML and it's getting tripped up there.

Duplicate of #760

**Closed by mmistakes** 2017-08-25 11:01 UTC

**Comment by deepaksood619** [comment] 2017-08-25 11:07
Thank you so much...
I was just wondering that, is there any way we can have a post that will show in archive and is linked to other post. i.e. clicking in the post will direct it to a post posted on another website?
Another use case - portfolio in grid view showing portfolio [example](https://mmistakes.github.io/minimal-mistakes/portfolio/), but clicking on a grid takes user to the link attached and not to blog or about of portfolio?
Can we achieve this?

**Comment by mmistakes** [comment] 2017-08-25 12:22
Sure. You can use the "Link Post" code to get an idea of how to do this. You'll most likely need to alter the theme some.

If you go to the [Year Archive](https://mmistakes.github.io/minimal-mistakes/year-archive/) and scroll down to **Post: Link** you'll see it links to an external site... and the link icon goes to the [post's permalink](https://mmistakes.github.io/minimal-mistakes/post%20formats/post-link/). 

Relevant source files:

- [`_includes/archive-single.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/archive-single.html#L27-L31)
- [`post-link.md`](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_posts/2010-03-07-post-link.md)

**Comment by deepaksood619** [comment] 2017-08-25 13:16
Thanks for the reply,
I exactly wanted this functionality.

But the problem now is that since there is a grid layout archive for my project portfolios, i am doing this in my portfolio.html
```html
<div class="grid__wrapper">
  {% assign items = site.portfolio | sort: 'date' | reverse %}
  {% for post in items %}
    {% include archive-single.html type="grid" %}
  {% endfor %}
</div>
```

and the problem is that in post with link, the `date` tag is not working, `excerpt` and `header` are working though.

How would i achieve a sort on date as my portfolio links are not created by date since i don't want that, i wanted a simple direct link for them, so i am not saving the files in collection with date prefixes. And if i don't do the date sort then the portfolios are shown in alphabetical order.

So how would i achieve this.

**Comment by deepaksood619** [comment] 2017-08-29 04:12
Sorry, i got the solution. Thanks. It was working, issue was on formatting.
