### ISSUE TITLE
How to integrate bootstrap?

### ISSUE THREAD

**Issue by stefansonntag** [mmistakes/minimal-mistakes#1552] opened 2018-02-25 17:38 UTC
- [x] This is a question about using the theme.
- [x] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [x] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

---

**Comment by mmistakes** [comment] 2018-02-25 17:39
Closing as this is a duplicate of #1518

**Closed by mmistakes** 2018-02-25 17:39 UTC
