### ISSUE TITLE
Theme not supported by GitHub

### ISSUE THREAD

**Issue by wilsonmar** [mmistakes/minimal-mistakes#1394] opened 2017-12-10 21:05 UTC
This is a question about using the theme.

After cloning to my account and pushing, I am getting this message from GitHub:

```
The page build completed successfully, but returned the following warning for the `master` branch:

You are attempting to use a Jekyll theme, "minimal-mistakes-jekyll", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```

**Comment by mmistakes** [comment] 2017-12-10 22:30
This is just a warning. GitHub Pages doesn't support 3rd party theme gems using the `theme` property in **_config.yml**. It only supports the `remote_theme` property.

Remove the following line and the error will go away:

```yaml
theme: minimal-mistakes-jekyll
```

Closing as this is a duplicate of #1366, #951

**Closed by mmistakes** 2017-12-10 22:30 UTC

**Comment by bingbing233** [comment] 2018-12-13 02:33
where is the sentence 'theme :minmal-mistakes-jekyll',is it in _comfig.yml?I just saw theme:lanscape @mmistakes
