### ISSUE TITLE
Algolia Search Not Working - js error

### ISSUE THREAD

**Issue by nomemory** [mmistakes/minimal-mistakes#1989] opened 2018-12-05 12:21 UTC
Hello,

I am trying to use Algolia as the search provider, but I am experiencing problems. 

Even if the index seems to be populated and the build is not reporting kind of errors, the search box is not showing any results.

1. My Gemfile configuration contains the `gem "jekyll-algolia"` plugin:

```
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-paginate"
  gem "jekyll-include-cache"
  gem "jekyll-algolia"
end
```

2. The `_config.yml` has search enabled I suspect Algolia correctly configured (the index is getting populated):

```
search: true
search_provider: algolia
algolia:
  application_id: <Application ID>
  index_name: <Index NAME>
  search_only_api_key: <Search-Only API Key>
  powered_by: true
```

3. The [site](http://www.mockneat.com) which is still a work in progress is live -> and you can actually see the error live there if you try to search something.

The console.log error I am receiving is:

```
(index):401 Uncaught TypeError: Cannot read property 'value' of undefined
    at hitTemplate ((index):401)
    at u (Template.js:147)
    at t.value (Template.js:29)
    at E (preact-compat.es.js:491)
    at t.render (preact-compat.es.js:502)
    at O (preact.esm.js:686)
    at O (preact.esm.js:712)
    at C (preact.esm.js:634)
    at E (preact.esm.js:814)
    at b (preact.esm.js:355)
hitTemplate @ (index):401
u @ Template.js:147
value @ Template.js:29
E @ preact-compat.es.js:491
(anonymous) @ preact-compat.es.js:502
O @ preact.esm.js:686
O @ preact.esm.js:712
C @ preact.esm.js:634
E @ preact.esm.js:814
b @ preact.esm.js:355
_ @ preact.esm.js:474
b @ preact.esm.js:397
y @ preact.esm.js:306
O @ preact.esm.js:727
C @ preact.esm.js:634
E @ preact.esm.js:800
b @ preact.esm.js:355
y @ preact.esm.js:306
k @ preact.esm.js:949
o @ preact-compat.es.js:149
(anonymous) @ hits.js:36
render @ connectHits.js:84
(anonymous) @ InstantSearch.js:317
n @ _arrayEach.js:15
r @ forEach.js:37
value @ InstantSearch.js:313
n.emit @ events.js:84
(anonymous) @ algoliasearch.helper.js:1245
n @ _arrayEach.js:15
r @ forEach.js:37
r._dispatchAlgoliaResponse @ algoliasearch.helper.js:1238
(anonymous) @ AlgoliaSearchCore.js:446
setTimeout (async)
e.exports @ exitPromise.js:6
(anonymous) @ AlgoliaSearchCore.js:445
Promise.then (async)
r._jsonRequest @ AlgoliaSearchCore.js:444
r.search @ AlgoliaSearchCore.js:572
r._search @ algoliasearch.helper.js:1204
r.search @ algoliasearch.helper.js:150
t @ connectSearchBox.js:110
(anonymous) @ search-box.js:359
```

Is there's something very simple and basic which I am missing ? 

Any suggestions ?

PS: Totally unrelated, congrats on the well-documented theme. If only all the projects had documentation like yours!

**Comment by nomemory** [comment] 2018-12-05 15:00
@mmistakes I don't experience the CORS error, but i think I found the issue.

In the Algolia Dashboard I receive this warning:

![screenshot at dec 05 16-55-23](https://user-images.githubusercontent.com/1010477/49521655-9bff5500-f8ae-11e8-8261-06f74cb6bfad.png)

The Algolia API doesn't return any `title` for when I hit search:

![image](https://user-images.githubusercontent.com/1010477/49521740-c6e9a900-f8ae-11e8-83ee-e79de6bd307d.png)

But the js code is looking for the `title` attribute:

![image](https://user-images.githubusercontent.com/1010477/49521871-fd272880-f8ae-11e8-9eb0-5ec6b55f7338.png)

So I believe this is related to InstantSearch.js .

**Comment by mmistakes** [comment] 2018-12-05 15:04
If you look at your index on Algolia do you have `titles`? Could be the index isn't being built properly with the Algolia gem that pushes it up.

For reference this is a sample of what I see for the MM demo site:

![image](https://user-images.githubusercontent.com/1376749/49522197-1dd28c80-f875-11e8-859e-8e2d6c36edbe.png)

**Comment by nomemory** [comment] 2018-12-05 15:08
@mmistakes exactly that. 

The `attribute` title doesn't exists on the indexed items.

**Comment by nomemory** [comment] 2018-12-05 15:11
I am quite a beginner with Jekyll, how do you specify a title for the page ?

With `page.title` in `.md` file header (before the `---`) ?

**Comment by mmistakes** [comment] 2018-12-05 15:14
You don't have to do anything special. Jekyll uses `title` in the front matter of post/page or if you don't assign it, it pulls it from the filename.

I think you're fine with Jekyll. The issue is with the Jekyll Algolia gem. Can you confirm what command you're using to build your site? What happens when you run `bundle exec jekyll algolia`? You should see a message letting you know how many records were found and if there were an issues.

**Comment by nomemory** [comment] 2018-12-05 15:20
For me it looks in a similar fashion, but the `title` attribute is still missing:

```
Processing site...
       Jekyll Feed: Generating feed for posts
Rendering to HTML (100%) |=================================================================================================================================================================================|
Extracting records (100%) |================================================================================================================================================================================|
Updating settings of index mockneat
Getting list of existing records
Updating records in index mockneat...
Records to delete: 0
Records to add: 424
✔ Indexing complete
```

My pages don't have any title property written "in clear". I will add them, re-index and see if the attribute gets added.

**Comment by mmistakes** [comment] 2018-12-05 15:23
That could be it then. Maybe there's some sort of failing with the Algolia Jekyll plugin that it needs `title` in the front matter.

**Comment by mmistakes** [comment] 2018-12-05 15:29
I don't think `title` is required for the plugin. The theme needs it to build the search listing views. That's why it was breaking for you.

https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/search/algolia-search-scripts.html#L22-L28

**Comment by nomemory** [comment] 2018-12-11 15:12
I think we can close this issue. This is actually not related to minimal-mistakes.

Thanks!

**Closed** 2018-12-11 15:48 UTC
Labels: Type: Support
