### ISSUE TITLE
page build failed for the `master` branch with the following error:

### ISSUE THREAD

**Issue by Rafael-Guzman** [mmistakes/minimal-mistakes#1881] opened 2018-10-08 16:43 UTC
Generating...
      Remote Theme: Using theme mmistakes/minimal-mistakes
  Liquid Exception: Liquid syntax error (line 16): Unknown tag 'include_cached' in /_layouts/default.html
jekyll 3.7.3 | Error:  Liquid syntax error (line 16): Unknown tag 'include_cached'

**Comment by mmistakes** [comment] 2018-10-08 16:55
Please have look through the closed issues before filing.
There are notes about this at the top of the README and in several locations of the documentation.

![image](https://user-images.githubusercontent.com/1376749/46622587-2f0f4f00-caf9-11e8-8955-86350ae3d613.png)

Closing as this is a duplicate of #1875, #1879

**Closed by mmistakes** 2018-10-08 16:55 UTC
Labels: Type: Duplicate

**Comment by Rafael-Guzman** [comment] 2018-10-08 17:07
thanks I appreciate it

**Comment by ajberlier** [comment] 2020-09-04 00:50
I am running into this issue as well. It works great on local but I get the follow github pages email for build failure. I did clone you repo and I am trying to build it exactly as is still without success.

The page build failed for the `master` branch with the following error:
The tag `include_cached` on line 15 in `/_layouts/default.html` is not a recognized Liquid tag.
