### ISSUE TITLE
Links being displayed in Chrome

### ISSUE THREAD

**Issue by AngerM** [mmistakes/minimal-mistakes#2228] opened 2019-08-07 05:53 UTC
## Environment
GIthub pages running 4.16.5
- Git repository URL: https://github.com/AngerM/angerm.github.io
- GitHub Pages hosted (if yes provide URL to site): https://www.mattanger.dev/
- Operating system: Mac OS 10.14.6
- Chrome: 75.0.3770.142 
- Firefox: 68.01

## Expected behavior
The links/follows in the `author` section or `footer` section don't display on Chrome but seem to work as expected on Firefox

Chrome:
![image](https://user-images.githubusercontent.com/1715525/62598023-c7eb3400-b89c-11e9-822a-187db90dffe0.png)

Firefox:
![image](https://user-images.githubusercontent.com/1715525/62598041-d33e5f80-b89c-11e9-959f-a326276a21c3.png)

**Comment by AngerM** [comment] 2019-08-07 07:09
Additional Data point: The mobile chrome view seems to work just fine. Chrome on Android displays the links in the follow menu as expected. I also made sure I tested with dev-tools open on desktop chrome and `disable cache` turned on to make sure it wasn't a bad caching issue, but the issue persists.

**Comment by mmistakes** [comment] 2019-08-07 12:07
This comes up a lot. It's not a theme issue, it's a content/adblocker in your browser. Some are overly aggressive and don't social media links and/or FontAwesome icons so it hides them.

This is why it works in Chrome for Android and not the desktop browser. Check your extensions and disable any content blockers.

Duplicate of: #2148, #1899, #1568, #423, #422, #421, #413

**Closed by mmistakes** 2019-08-07 12:07 UTC

**Comment by AngerM** [comment] 2019-08-07 16:27
Interesting. Is there a difference to how these links are rendered in chrome vs firefox? because I have the same ublock setup on both, which is why I hadn't considered ublock being an issue.

**Comment by mmistakes** [comment] 2019-08-07 16:29
No idea, that's a question for the plugin author and browser makers.
Have you tried disabling it to see if the links show up in Chrome? Same plugin might not have same coding for the various browsers it extends.
