### ISSUE TITLE
How to show full sized image from clicking smaller image

### ISSUE THREAD

**Issue by GRomR1** [mmistakes/minimal-mistakes#2380] opened 2020-01-24 18:32 UTC
## Summary
Hi,
Maybe someone has asked before about this.  How to show a full-sized image from clicking smaller image? 

## Motivation

I want to see a full-size image **by click** on small image. After that, I want to quickly return back on page (i.e. click again on the image). Like [modal windows](https://www.w3schools.com/howto/howto_css_modal_images.asp). 

The [galleries](https://mmistakes.github.io/minimal-mistakes/docs/helpers/#gallery) have a great and similar functionality. But it needs to write so much code to define the image.

I think it should be easy. It can be implemented for example (in markdown):
```
{% include image caption="Some meaningful description" src="{{ site.url }}{{ site.baseurl }}/assets/images/filename.jpg" class="" %}
```

## Drawbacks

What do you think about that?

**Comment by mmistakes** [comment] 2020-01-24 19:41
You can do this now. Link a small image to a large image using either HTML or Markdown (see below for sample) and the theme will automatically open in a lightbox overlay.

```markdown
[![small image](/path-to-image/small.jpg)](/path-to-image/large.jpg)
```

**Comment by mmistakes** [comment] 2020-01-24 19:42
Closing as this is a duplicate of #2088

**Closed by mmistakes** 2020-01-24 19:42 UTC
Labels: Type: Support
