### ISSUE TITLE
Pagination nav breakage when adjusting paginate_path within _config.yml

### ISSUE THREAD

**Issue by jaybe-jekyll** [mmistakes/minimal-mistakes#1855] opened 2018-09-28 17:34 UTC
## Description

Changing _config.yml value, `paginate_path:` to  `/page/:num/` results in pagination navigation breaking. For example, previous page link becomes, e.g. `http://site.local:4000/page/:num/`

## Environment

Current/Stable

## Expected behavior

Correct and adjusted pagination navigation.

## Steps to reproduce the behavior

Adjust _config.yml value, `paginate_path:` to  `/page/:num/`

**Comment by mmistakes** [comment] 2018-09-29 00:50
You have a public/test repo that illustrates this bug?
I just modified the [`/test` repo](https://github.com/mmistakes/minimal-mistakes/tree/master/test) the theme has and changed `paginate_path: /page/:num/` and everything works as expected.

![screen shot 2018-09-28 at 8 49 19 pm](https://user-images.githubusercontent.com/1376749/46238971-174d0380-c360-11e8-8b99-a9c76c913f20.png)

**Comment by jaybe-jekyll** [comment] 2018-09-29 00:56
I should have mentioned the additional changes of adding gem `jekyll-paginate-v2` and its base configuration within `_config.yml`.

jekyll-paginate-v2 advised to unset `paginate:` or set to `off`. I commented it out.

**Comment by mmistakes** [comment] 2018-09-29 01:00
Theme isn't compatible with that plugin yet. The pagination links need to
be rebuilt for it.

Closing as this is a duplicate of what is already summarized in #1307.

**Closed** 2018-09-29 00:59 UTC
Labels: Status: Feedback Needed
