### ISSUE TITLE
How to move left and right sidebar further apart and expand width of body?

### ISSUE THREAD

**Issue by Wei2624** [mmistakes/minimal-mistakes#1930] opened 2018-11-04 22:43 UTC
Hi @mmistakes ,

Thanks for the work again. 

I am trying to give more space to the body of text so that two sidebars are pushed further to left and right. I am kindly wondering which variable I should change without damaging other functionality.

Thanks for your help.

**Comment by mmistakes** [comment] 2018-11-04 23:32
Duplicate of #1373, #1265, #623, #384, #74

**Closed by mmistakes** 2018-11-04 23:32 UTC

**Comment by Wei2624** [comment] 2018-11-09 22:05
@mmistakes Thanks for pointing out. I can successfully extend the right sidebar to further right. However, I am wondering if I can extend left sidebar to further left as well. Is there a simple change to that?

**Comment by mmistakes** [comment] 2018-11-09 22:08
No simple way. You write some custom CSS just like you would for the right sidebar. 

You'll have to reduce the with of the main content to make room for the left increase.

**Comment by Wei2624** [comment] 2018-11-10 17:14
@mmistakes Thanks for the reply. 

Also, another question is that did you have `padding-left` as well? I feel like you also "fake" some empty space on the left as well. Is it what you did?

**Comment by mmistakes** [comment] 2018-11-10 18:18
Your browser's web inspector is what you'll want to use here. Inspect elements and it'll tell you the exact CSS I'm using.
