### ISSUE TITLE
Liquid exception: Liquid syntax error (line 16): Unknown tag 'include_cached' in /_layouts/default.html

### ISSUE THREAD

**Issue by alexmanrique** [mmistakes/minimal-mistakes#1879] opened 2018-10-06 17:29 UTC
When I run jekyll 3.8.3 with minimal-mistakes remote-theme locally in my macosx I get the following error:

$> bundle exec jekyll build --trace --verbose

Incremental build: disabled. Enable with --incremental
      Generating...
Invalid theme folder: _sass
      Remote Theme: Using theme mmistakes/minimal-mistakes
  Liquid Exception: Liquid syntax error (line 16): Unknown tag 'include_cached' in /_layouts/default.html
jekyll 3.8.3 | Error:  Liquid syntax error (line 16): Unknown tag 'include_cached'
***$ bundle exec jekyll build --trace --verbose
  Logging at level: debug
Configuration file: /Users/***/git/blog/_config.yml
      GitHub Pages: github-pages v192
      GitHub Pages: jekyll v3.8.3
             Theme: jekyll-theme-primer
      Theme source: /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-theme-primer-0.5.3
         Requiring: jekyll-github-metadata
Dotenv not found. Skipping
         Requiring: jekyll-seo-tag
         Requiring: jekyll-feed
         Requiring: jekyll-coffeescript
         Requiring: jekyll-commonmark-ghpages
         Requiring: jekyll-gist
         Requiring: jekyll-github-metadata
         Requiring: jekyll-paginate
         Requiring: jekyll-relative-links
         Requiring: jekyll-optional-front-matter
         Requiring: jekyll-readme-index
         Requiring: jekyll-default-layout
         Requiring: jekyll-titles-from-headings
         Requiring: jekyll-remote-theme
   GitHub Metadata: Initializing...
            Source: /Users/****/git/blog
       Destination: /Users/****/git/blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
             Theme: mmistakes/minimal-mistakes
      Theme source: /private/var/folders/l4/9bx0v9p96h9b7m202j2g33mw0000gn/T/jekyll-remote-theme-20181006-824-1eu4dym
Invalid theme folder: _sass
      Remote Theme: Using theme mmistakes/minimal-mistakes
      Remote Theme: Downloading https://codeload.github.com/mmistakes/minimal-mistakes/zip/master to /var/folders/l4/9bx0v9p96h9b7m202j2g33mw0000gn/T/jekyll-remote-theme-20181006-824-18ii6lo.zip
      Remote Theme: Unzipping /var/folders/l4/9bx0v9p96h9b7m202j2g33mw0000gn/T/jekyll-remote-theme-20181006-824-18ii6lo.zip to /private/var/folders/l4/9bx0v9p96h9b7m202j2g33mw0000gn/T/jekyll-remote-theme-20181006-824-1eu4dym
       EntryFilter: excluded /CNAME
       EntryFilter: excluded /Gemfile
       EntryFilter: excluded /Gemfile.lock
           Reading: _posts/2017-07-21-builds-lentos-deploys-rapidos.md
           Reading: _posts/2017-07-21-slow-builds-fast-deploys.md
           Reading: _posts/2017-10-21-host-personal-website-for-free-with-github-pages.md
           Reading: _posts/2017-11-05-modern-javaee-design-patterns-book-review.md
           Reading: _posts/2017-11-11-retrospectives-learning-from-the-past.md
           Reading: _posts/2017-12-02-tips-to-understand-code.md
           Reading: _posts/2018-01-05-tips-to-write-clean-code.md
           Reading: _posts/2018-01-15-metrics-in-your-java-application.md
           Reading: _posts/2018-01-24-managing-maven-dependencies.md
           Reading: _posts/2018-01-31-the-importance-of-code-reviews.md
           Reading: _posts/2018-02-23-dependency-injection-in-code.md
           Reading: _posts/2018-03-24-blockchain-la-revolucion.md
           Reading: _posts/2018-07-08-migrating-from-windows-to-ubuntu.md
           Reading: _posts/2018-08-02-migrate-to-the-last-version.md
           Reading: _posts/2018-09-22-improving-jpa-queries.md
        Generating: JekyllOptionalFrontMatter::Generator finished in 0.000262 seconds.
        Generating: JekyllReadmeIndex::Generator finished in 0.003106 seconds.
        Generating: JekyllFeed::Generator finished in 0.001279 seconds.
        Generating: Jekyll::Paginate::Pagination finished in 0.001474 seconds.
        Generating: JekyllRelativeLinks::Generator finished in 7.4e-05 seconds.
        Generating: JekyllDefaultLayout::Generator finished in 0.000379 seconds.
        Generating: JekyllTitlesFromHeadings::Generator finished in 3.2e-05 seconds.
         Rendering: _posts/2017-07-21-builds-lentos-deploys-rapidos.md
  Pre-Render Hooks: _posts/2017-07-21-builds-lentos-deploys-rapidos.md
  Rendering Liquid: _posts/2017-07-21-builds-lentos-deploys-rapidos.md
         Requiring: rouge
  Rendering Markup: _posts/2017-07-21-builds-lentos-deploys-rapidos.md
  Rendering Layout: _posts/2017-07-21-builds-lentos-deploys-rapidos.md
     Layout source: theme
         Rendering: _posts/2017-07-21-builds-lentos-deploys-rapidos.md/#excerpt
  Pre-Render Hooks: _posts/2017-07-21-builds-lentos-deploys-rapidos.md/#excerpt
  Rendering Markup: _posts/2017-07-21-builds-lentos-deploys-rapidos.md/#excerpt
         Rendering: _posts/2018-09-22-improving-jpa-queries.md/#excerpt
  Pre-Render Hooks: _posts/2018-09-22-improving-jpa-queries.md/#excerpt
  Rendering Markup: _posts/2018-09-22-improving-jpa-queries.md/#excerpt
         Rendering: _posts/2018-08-02-migrate-to-the-last-version.md/#excerpt
  Pre-Render Hooks: _posts/2018-08-02-migrate-to-the-last-version.md/#excerpt
  Rendering Markup: _posts/2018-08-02-migrate-to-the-last-version.md/#excerpt
         Rendering: _posts/2018-07-08-migrating-from-windows-to-ubuntu.md/#excerpt
  Pre-Render Hooks: _posts/2018-07-08-migrating-from-windows-to-ubuntu.md/#excerpt
  Rendering Markup: _posts/2018-07-08-migrating-from-windows-to-ubuntu.md/#excerpt
         Rendering: _posts/2018-03-24-blockchain-la-revolucion.md/#excerpt
  Pre-Render Hooks: _posts/2018-03-24-blockchain-la-revolucion.md/#excerpt
  Rendering Markup: _posts/2018-03-24-blockchain-la-revolucion.md/#excerpt
  Liquid Exception: Liquid syntax error (line 16): Unknown tag 'include_cached' in /_layouts/default.html
bundler: failed to load command: jekyll (/usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/exe/jekyll)
Liquid::SyntaxError: Liquid syntax error (line 16): Unknown tag 'include_cached'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/document.rb:23:in `unknown_tag'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/document.rb:11:in `block in parse'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:33:in `parse'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/document.rb:10:in `parse'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/document.rb:5:in `parse'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:132:in `parse'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:116:in `parse'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/liquid_renderer/file.rb:12:in `parse'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/renderer.rb:121:in `render_liquid'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/renderer.rb:195:in `render_layout'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/renderer.rb:158:in `place_in_layouts'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/renderer.rb:88:in `render_document'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/renderer.rb:62:in `run'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/site.rb:479:in `render_regenerated'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/site.rb:463:in `each'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/site.rb:463:in `block in render_docs'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/site.rb:462:in `each_value'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/site.rb:462:in `render_docs'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/site.rb:191:in `render'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/site.rb:71:in `process'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/command.rb:28:in `process_site'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/commands/build.rb:65:in `build'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/commands/build.rb:36:in `process'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/exe/jekyll:15:in `<top (required)>'
      Remote Theme: Cleaning up /private/var/folders/l4/9bx0v9p96h9b7m202j2g33mw0000gn

This is my Gemfile :

source "https://rubygems.org"
gem 'jekyll-remote-theme'
gem "github-pages", group: :jekyll_plugins
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

This is the repo of my blog using jekyll and minimal-mistakes : https://github.com/alexmanrique/blog

thanks

regards

**Comment by mmistakes** [comment] 2018-10-06 17:31
Duplicate of #1875. See that issue for the fix.

**Closed by mmistakes** 2018-10-06 17:31 UTC
