### ISSUE TITLE
Header font appears very dull and small

### ISSUE THREAD

**Issue by ansiblejunky** [mmistakes/minimal-mistakes#1872] opened 2018-10-04 15:33 UTC
I have not changed any font settings from your theme, and I feel the header I am seeing is not the same as what you get on your demo.  Here is what I am seeing..
![image](https://user-images.githubusercontent.com/14311849/46485113-e6c9f700-c7af-11e8-91e5-2e49b629d746.png)

Additionally, I noticed on mobile devices the normal paragraph text is super small. I would say this needs to increase in size a bit for general readability on mobile devices. How can I best do that with your theme? I assume I need to change the CSS somewhere but it would only need to change for mobile devices.

Thanks for the help.

**Comment by mmistakes** [comment] 2018-10-04 15:39
Not sure on the difference in font you're seeing between the demo. The font family set uses "system fonts" so depending on the environment you're looking at it will change as macOS, Windows, Linux, Android, etc. all use different system fonts.

As for bumping up the `font-size`. Do a search through the closed issues. I've covered how to change them too many times to count.

**Comment by mmistakes** [comment] 2018-10-04 15:40
Closing as this is a duplicate of #1352, #1219, and #1184.

**Closed by mmistakes** 2018-10-04 15:40 UTC
Labels: Type: Duplicate, Type: Support

**Comment by ansiblejunky** [comment] 2018-10-04 17:10
Thank you. You respond to these questions/bugs super fast! Appreciate it.
