### ISSUE TITLE
Reduce the overall size of site

### ISSUE THREAD

**Issue by jongmin92** [mmistakes/minimal-mistakes#793] opened 2017-01-25 16:24 UTC
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- Using minimal-mistakes-jekyll 4.1.1 from source at .
- jekyll 3.3.1
- Using github pages

---

## Expected behavior

 I want to reduce the overall size of the site

## Steps to reproduce the behavior

 Hello.
How can I reduce the overall size of your site?
For example, I want to reduce from 100% to 80%.

**Comment by mmistakes** [comment] 2017-01-25 16:26
By size what do you mean exactly? Page width? File size of outputted HTML? etc.?

**Comment by mmistakes** [comment] 2017-01-25 16:27
If it's page width related check this old issue where I explain where to look and what you'll need to modify in the CSS.

https://github.com/mmistakes/minimal-mistakes/issues/384

**Comment by jongmin92** [comment] 2017-01-25 16:42
Now> 100%
<img width="1440" alt="2017-01-26 1 29 34" src="https://cloud.githubusercontent.com/assets/15906302/22299336/0266c328-e367-11e6-8ef8-10fadf61f54b.png">
I want an overall size of 80%. like this image (It's like **zooming out** the browser screen.)
<img width="1440" alt="2017-01-26 1 30 06" src="https://cloud.githubusercontent.com/assets/15906302/22299339/03d56804-e367-11e6-9559-d4a89efd8278.png">

**Comment by mmistakes** [comment] 2017-02-14 17:08
Closing this issue as it appears to be duplicate of #384. If you have more details to share feel free to re-open.

**Closed by mmistakes** 2017-02-14 17:08 UTC
Labels: Status: Pending
