### ISSUE TITLE
could u tell me how to change the fontsize of the pages

### ISSUE THREAD

**Issue by rouor** [mmistakes/minimal-mistakes#2112] opened 2019-03-29 15:52 UTC
first I try to change the size of font in assets/css/main.scss 
the index.html changed.
however I want to change fontsize of pages, make it smaller. But i do not know how todo？

can u let me know where to change it ?
thanks very much

**Comment by mmistakes** [comment] 2019-03-29 15:54
Please search through the issues, you'll find your answer there.

Closing as this is a duplicate of #1352, #1219, and #1184.

**Closed by mmistakes** 2019-03-29 15:54 UTC

**Comment by rouor** [comment] 2019-03-30 01:36
> Please search through the issues, you'll find your answer there.
> 
> Closing as this is a duplicate of #1352, #1219, and #1184.

thanks a lot
