### ISSUE TITLE
`position: sticky` causes sidebar overlap in Chrome

### ISSUE THREAD

**Issue by kvz** [mmistakes/minimal-mistakes#752] opened 2017-01-05 15:54 UTC
Hi, thanks for minimal-mistakes! I just deployed it yesterday on kvz.io and loving it so far. One person on [reddit reported](https://www.reddit.com/r/webdev/comments/5m5pk9/introducing_lanyon/) it looked weird - but it looks fine in my browsers. 

The page in question is http://kvz.io/blog/2017/01/04/introducing-lanyon/ - Beyond social buttons, i did not make any layout changes, only config & markdown.

For convenience here is a direct screenshot for Chrome 56 on windows: http://i.imgur.com/BxfzHrn.png

**Comment by mmistakes** [comment] 2017-01-05 16:05
Does the overlap happen on all pages that have the author sidebar? or just that one?

I'm on Chrome 55 on Windows and not able to reproduce it. Are there any sort of JavaScript errors in the console or is it disabled for any reason? There is a JS polyfill for `position: sticky` used on the sidebar that could be potentially running amok.

Other than that I'm at a loss as to what's going on.

**Comment by mmistakes** [comment] 2017-01-05 16:13
OK, looks like it's related to `position: sticky` since it was [added to the beta version last month](https://blog.chromium.org/2016/12/chrome-56-beta-not-secure-warning-web.html). Will have to test it out and hopefully get a fix out before `position: sticky` support hits the stable release of Chrome... whenever that is.

**Comment by mmistakes** [comment] 2017-01-05 16:41
Tested on beta Chrome 56 on Windows and all works as it should.

![chrome_56](https://cloud.githubusercontent.com/assets/1376749/21688610/87a84200-d33b-11e6-8229-4891ee92348e.jpg)

![lanyon-grab](https://cloud.githubusercontent.com/assets/1376749/21688694/d7549696-d33b-11e6-82d9-734d21c25039.gif)

With `position: sticky` landing in Chrome stable soon seems like a good time to drop the polyfill. Wasn't adding much anyways and likely won't be missed in older browsers or IE that don't currently support it.

Still not sure why it's broken for that redditor, could be something JS related. I know there's stuff in the theme that was added awhile back that tests the width of things to trigger the sticky polyfill, and that could be borked for whatever reason.

**Comment by kvz** [comment] 2017-01-05 17:07
Blown away by your care and thoroughness in handling this issue! Humbling! ❤️

**Comment by mmistakes** [comment] 2017-01-05 17:10
I do what I can :wink:

In the end I took out the polyfill. In Firefox, Safari, and Chrome 56 the sidebar will "stick" as it should. On older browsers it scrolls with the rest of the page, which isn't so bad either.

If you're interested in making the changing it's pretty small and in [this commit](https://github.com/mmistakes/minimal-mistakes/commit/55843c5dca8fcf5ff83e48ace202fc529d58ae14). I'll roll it out officially in the next release.

**Comment by NathanHeffley** [comment] 2017-01-05 18:11
You need to test on bigger screen sizes. The bug only appears when the browser is over 1150px wide and then it jumps back to working again for a little bit until the browser gets to be over 1400px wide. It appears from the GIF you posted that you didn't test on anything wider than maybe 1000px.

**Comment by mmistakes** [comment] 2017-01-05 18:45
> You need to test on bigger screen sizes. The bug only appears when the browser is over 1150px wide and then it jumps back to working again for a little bit until the browser gets to be over 1400px wide. It appears from the GIF you posted that you didn't test on anything wider than maybe 1000px.

@NathanHeffley Definitely not the case. It maybe hard to tell from the GIF but the screen was much wider than 100px.

Tested on both Windows and Mac Chrome 56 (beta) and couldn't reproduce the overlap.

![screen shot 2017-01-05 at 1 39 31 pm](https://cloud.githubusercontent.com/assets/1376749/21692904/eeecb534-d34c-11e6-99a0-bd0c71c80fa8.png)

Screen width `1875px`:

![screen shot 2017-01-05 at 1 39 48 pm](https://cloud.githubusercontent.com/assets/1376749/21692911/f2a9419c-d34c-11e6-982b-4e75ca7d5dd2.png)

Curious to know if you have any plugins installed that might mess with JS or noticed any script errors in the console.

**Comment by mmistakes** [comment] 2017-01-24 15:22
Fixed in https://github.com/mmistakes/minimal-mistakes/releases/tag/4.2.0

**Closed by mmistakes** 2017-01-24 15:22 UTC
Labels: Type: Bug

**Comment by kvz** [comment] 2017-01-24 16:44
Getting 

```
Could not find gem 'minimal-mistakes-jekyll (= 4.2.0)'
```

I should probably wait a while before it hits rubygems, just sharing in case

**Comment by mmistakes** [comment] 2017-01-24 16:48
@kvz Stange. It should be there, along with `4.2.1`. Unless it hasn't fully propagated. https://rubygems.org/gems/minimal-mistakes-jekyll/versions/4.2.1
