### ISSUE TITLE
Geme theme install error

### ISSUE THREAD

**Issue by inetbiz** [mmistakes/minimal-mistakes#2151] opened 2019-05-10 00:55 UTC
I have removed all files and folders per https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/ All the other files are default. I edited config to choose theme. I get this error upon build: ```Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    Invalid US-ASCII character "\xE2" on line 54```
The assets folder was emptied and so was the local cache.

**Comment by inetbiz** [comment] 2019-05-10 00:57
```
Using concurrent-ruby 1.1.5
Using i18n 0.9.5
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.3
Using public_suffix 3.0.3
Using addressable 2.6.0
Using bundler 2.0.1
Using colorator 1.1.0
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using multipart-post 2.1.0
Using faraday 0.15.4
Using ffi 1.10.0
Using forwardable-extended 2.6.0
Using gemoji 3.0.1
Using mini_portile2 2.4.0
Using nokogiri 1.10.3
Using html-pipeline 2.11.0
Using rb-fsevent 0.10.3
Using rb-inotify 0.10.0
Using sass-listen 4.0.0
Using sass 3.7.4
Using jekyll-sass-converter 1.5.2
Using ruby_dep 1.5.0
Using listen 3.1.5
Using jekyll-watch 2.2.1
Using kramdown 1.17.0
Using liquid 4.0.3
Using mercenary 0.3.6
Using pathutil 0.16.2
Using rouge 3.3.0
Using safe_yaml 1.0.5
Using jekyll 3.8.5
Using jekyll-data 1.0.0
Using jekyll-feed 0.12.1
Using sawyer 0.8.2
Using octokit 4.14.0
Using jekyll-gist 1.5.0
Using jekyll-include-cache 0.2.0
Using jekyll-paginate 1.1.0
Using jekyll-sitemap 1.3.1
Using jemoji 0.11.0
Using minimal-mistakes-jekyll 4.16.3
```

**Comment by mmistakes** [comment] 2019-05-10 01:21
It's an issue with your Ruby environment. Search old issues as I believe there are solutions there.

The Jekyll repo also has the same issue with some pointers on how to correct it.

**Comment by mmistakes** [comment] 2019-05-10 01:25
Duplicate of #1809

**Closed by mmistakes** 2019-05-10 01:25 UTC
