### ISSUE TITLE
Hardcoded date formats

### ISSUE THREAD

**Issue by alexandrevicenzi** [mmistakes/minimal-mistakes#2534] opened 2020-05-15 12:54 UTC
## Summary

Date format is hard coded to `"%B %-d, %Y"` in many places.

## Motivation

This date format does not goes well in Portuguese.

PT-BR uses `DD/MM/YYYY` format, or the long version `15 de Maio de 2020`, as i18n does not work it shows as `May 15, 2020`.

Even with some hacks to translate May to Maio it would look like `Maio 15, 2020`, this does not make much sense in PT-BR.

It would be nice to have a settings called `date_format` or something like where I could set all dates to the appropriate format in my language.

## Drawbacks

I need to hack the theme to change to `"%d/%m/%Y"` in multiple places.

**Comment by mmistakes** [comment] 2020-05-15 13:24
Closed as this is a duplicate of #815... see my response there.

> As far as localizing the date. Ideally Jekyll core would support it instead of having to resort to a bunch of Liquid code. Something like this was proposed but appears to have gone stale [jekyll/jekyll#5478](https://github.com/jekyll/jekyll/issues/5478)

**Closed by mmistakes** 2020-05-15 13:24 UTC

**Comment by alexandrevicenzi** [comment] 2020-05-15 14:06
Upstream issue was closed, that's never going to be implemented.
