### ISSUE TITLE
Button For Light/Dark Theme Switching

### ISSUE THREAD

**Issue by khanfarhan10** [mmistakes/minimal-mistakes#2742] opened 2020-11-25 09:48 UTC
## Summary
Wouldn't it be great to add a two theme switching button feature to the website:   
A button that would change the theme right away and would be available on all pages on the top navigation menu, possibly close to the search button on top?

Maybe include something in the theme configuration file as :
- Light_Dark_Button : true/ false
- Light_Theme : aqua
- Dark_Theme : neon

## Motivation
I thought of looking at some articles and found these : 
- https://medium.com/@derekkedziora/how-to-add-a-dark-mode-toggle-to-a-jekyll-site-a76dac00128d
- https://laptrinhx.com/how-to-add-a-dark-mode-toggle-to-a-jekyll-site-2605890340/

However, these documents don't cover the themes that minimal mistakes uses, aka : 

| aqua | neon | plum | dirt | mint | sunrise | air | contrast | dark |

## Drawbacks
None that I know of , except that it may cause the one navigation menu item to maybe go to the sidebar with three horizontal bars?

**Comment by iBug** [comment] 2020-11-25 09:51
#2033

**Comment by mmistakes** [comment] 2020-11-25 13:06
Closing as this is a duplicate of #2033

**Closed by mmistakes** 2020-11-25 13:06 UTC
Labels: Type: Duplicate
