### ISSUE TITLE
How to change font and font size?

### ISSUE THREAD

**Issue by randomwalk94** [mmistakes/minimal-mistakes#1514] opened 2018-02-02 01:26 UTC
- [ x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [x ] I am using the latest version of the theme.
  - [x ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.9
- **Jekyll version:** 3.7.2
- **GitHub Pages hosted:** yes
- **Operating system:** Mac 

---

## Issue

I just want to make the font a little bit smaller.

**Comment by mmistakes** [comment] 2018-02-02 01:36
Please search through the issues, you'll find your answer there.

Closing as this is a duplicate of #1352, #1219, and #1184.

**Closed by mmistakes** 2018-02-02 01:36 UTC
