### ISSUE TITLE
Content area of blog posts becomes much narrower in full-screen mode

### ISSUE THREAD

**Issue by quangminhtran** [mmistakes/minimal-mistakes#1722] opened 2018-06-29 06:18 UTC
## Description

GOOD behavior: In a non-full-screen mode of certain height/width, the content area of blog post is wide enough. 

<img width="1282" alt="minimal_mistakes_good" src="https://user-images.githubusercontent.com/8310586/42076197-572c5a52-7b74-11e8-8360-8ab85f65bd59.png">

BAD behavior: In full-screen mode, the content area suddenly becomes much narrower (this is bad!).

<img width="1436" alt="minimal_mistakes_bad" src="https://user-images.githubusercontent.com/8310586/42076128-12ad1204-7b74-11e8-843b-6974c769f337.png">

## Environment

- Minimal Mistakes version: latest, cloned from master
- Ruby gem or remote theme version:
- Jekyll version: 3.8.3
- Git repository URL: https://github.com/mmistakes/minimal-mistakes
- Operating system: MacOS
- GitHub Pages hosted (if yes provide URL to site): No

---

## Expected behavior

I would expect that the content area of blog posts remain wide and does not become much **narrower*** as depicted in the screenshot above.

## Steps to reproduce the behavior

See description.

**Comment by mmistakes** [comment] 2018-06-29 10:55
This is intentional.

If you want to override this behavior set `classes: wide` in your post's front matter like in [this example](https://mmistakes.github.io/minimal-mistakes/markup-text-readability-wide-page/).

Closing as this is a duplicate of #1373, #1265, #623, #384, #74

**Closed by mmistakes** 2018-06-29 10:55 UTC
